### ISSUE TITLE
how to not block  python + nodejs ?

### ISSUE THREAD

**Issue by Olmer1st** [0rpc/zerorpc-python#152]
Hi,

We started to use this library several months ago and when we started to do massive tests we saw that sometime the server blocked for other requests.
For example (server in python, client in nodejs):
**server**

```
#!/usr/bin/python
import signal
import sys
import zerorpc
import wget
from datetime import datetime

def getDateTimeNowString():
    string = datetime.now().strftime("%Y%m%d%H%M%S%f")
    return string


def exit_handler(signal, frame):
    print "You are now leaving the Python sector."
    sys.exit(0)


class todo(object):
    def __init__(self):
        pass

    def executeCommand(self):
        print datetime.now()
        filename = wget.download('some url to xml',
                                 out="{0}_{1}.xml".format("test", getDateTimeNowString()))
        return filename

signal.signal(signal.SIGINT, exit_handler)

try:
    server = zerorpc.Server(todo(), heartbeat=360)
    bindingData = "{0}:{1}".format("tcp://0.0.0.0", 1234)
    server.bind(bindingData)
    print "RPC Channels Server bound to {0}".format(bindingData)
    server.run()
except Exception as e:
    print str(e)
```

**client**

```
const times = x => f => {
    if (x > 0) {
        f()
        times(x - 1)(f)
    }
};
const callbackFunction = function(err, result, start) {
    const end = new Date() - start;
    console.log('Download finished, took: ', end + " ms", "\r\nresult: ", result);
}
const zerorpc = require('zerorpc');
const client = new zerorpc.Client({
        timeout: 360,
        heartbeatInterval: 360000
    });
const uri = "tcp://127.0.0.1:1234";
console.log("Connecting to rpc with URI ", uri);
client.connect(uri);
const start = new Date();
console.log("Started download, please wait");
times(5)(()=>{
client.invoke("executeCommand", function(error, res, more) {
        callbackFunction(error,res, start);
});
});
```

If to execute, you will see:
Connecting to rpc with URI  tcp://127.0.0.1:1234
Started download, please wait
Started download, please wait
Started download, please wait
Started download, please wait
Started download, please wait
Download finished, took:  5054 ms
result:  {"type":"Buffer","data":[116,101,115,116,95,50,48,49,54,49,48,50,55,49,55,51,52,48,49,57,57,50,56,51,53,46,120,109,108]}
Download finished, took:  15640 ms
result:  {"type":"Buffer","data":[116,101,115,116,95,50,48,49,54,49,48,50,55,49,55,51,52,48,55,48,52,49,52,55,56,46,120,109,108]}
Download finished, took:  15640 ms
result:  {"type":"Buffer","data":[116,101,115,116,95,50,48,49,54,49,48,50,55,49,55,51,52,49,51,48,49,51,50,50,52,46,120,109,108]}
Download finished, took:  29956 ms
result:  {"type":"Buffer","data":[116,101,115,116,95,50,48,49,54,49,48,50,55,49,55,51,52,49,55,54,51,48,57,52,55,46,120,109,108]}
Download finished, took:  29956 ms
result:  {"type":"Buffer","data":[116,101,115,116,95,50,48,49,54,49,48,50,55,49,55,51,52,50,53,56,49,55,57,48,51,46,120,109,108]}

As you see each invoke wait until previous done.
How to prevent this blocking?

And, why instead string (name of file) we see buffer in nodejs?
In python you can see:
2016-10-27 17:34:01.992810
2016-10-27 17:34:07.041445
2016-10-27 17:34:13.013206
2016-10-27 17:34:17.630839
2016-10-27 17:34:25.817877
All requests started not the same time....
Please help, we currently stuck with this problems.

**Comment by bombela** [comment]
Your server code looks it is blocking that's the reason why it... blocks. You should not have to change the default heartbeat. To me it looks like you are changing it to some high value because you are blocking the whole python process during the wget download.

Your code must be gevent compatible, and never block. One easy workaround in your case would be to run the wget code inside its own thread, and waiting on the completion via a gevent queue. This would keep the iolopp on the main thread running while the wget process is blocked. You can even use a [threadpool](http://www.gevent.org/gevent.threadpool.html) for this.

Of course the best solution would be to have a gevent compatible ([random example](https://github.com/kennethreitz/grequests)) version of your wget download.

**Comment by Olmer1st** [comment]
Thanks.
and what about second question?

**Comment by bombela** [comment]
Check the type that you are returning from the python side. Note that you should be able to convert the buffer to a string in nodejs. As I understand it, nodejs strings must be utf8, anything else goes in a buffer, so you have to convert and handle errors. Of course you could return an utf8 string fron python. Since you are seemingly returning a filename and filename on most unix are not utf8, but blob of bytes, I suspect you are in fact returning non-utf8 string.
