### ISSUE TITLE
How I can daemonizer zerorpc with python?

### ISSUE THREAD

**Issue by yxxhero** [0rpc/zerorpc-python#161]
How I can daemonizer zerorpc with python? thanks!!!

**Comment by bombela** [comment]
Not sure to understand your question, can you try to be more explicit?

**Comment by yxxhero** [comment]
sorry ! I am a Chinese.My English is not very good。
when I use python-daemon module to  daemonize my zerorpc server so it can continue running in the background. but  when I connect to the server , it will be timeout. I want to know why?

**Comment by bombela** [comment]
No worries, with more details I understand you just fine. English is not my
first language either.

I don't know python-damon and there seems to be few packages with the same
name.

If it timeouts it's probably because something is blocking the gevent
ioloop.

You have to make sure that every package you use is compatible with gevent.
This is because zerorpc itself uses gevent.

On Sat, Mar 18, 2017, 19:00 yxxhero <notifications@github.com> wrote:

sorry ! I am a Chinese.My English is not very good。
when I use python-daemon module to daemonize my zerorpc server so it can
continue running in the background. but when I connect to the server , it
will be timeout. I want to know why?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/0rpc/zerorpc-python/issues/161#issuecomment-287588544>,
or mute the thread

**Comment by yxxhero** [comment]
What should i do to daemonize my zerorpc server so it can continue running in the background? Thank you very much, I really like zerorpc.

**Comment by bombela** [comment]
Use a service runner, like systemd, or supervisord. You can also run your process via "nohup" (man nohup) before terminating the control terminal. If you want your process to have the init process (pid 1) as a parent, and lose its process session, simply double fork before doing anything. Hope this helps.

**Comment by yxxhero** [comment]
Hope to learn more about you,thank you very much.
I work with linux,I am studing python

**Comment by petmakris** [comment]
@bombela This is not what he is asking.
The question seems to be how to start a server (server.run()) in background from within the python code.
It's blocking and threads are not supported due to gevent (zerorpc based upon)

**Comment by jandykwan** [comment]
@petmakris any solutions? thanks a lot

**Comment by bombela** [comment]
I do not understand the problem fully. If you call run() from a coroutine, it will run the zerorpc server loop in the "background". And as long as the rest of your program is gevent aware everything will behave properly.

**Comment by rtobar** [comment]
Not sure, but are you looking for something like this?

```
import daemon
import zerorpc

class HelloRPC(object):
    def hello(self, name):
        return("Hello, %s" % name)

def start():
    s = zerorpc.Server(HelloRPC())
    s.bind("tcp://0.0.0.0:4242")
    s.run()

if __name__ == '__main__':
    with daemon.DaemonContext():
        start()
```

You can later signal the daemon process to stop if you know the PID. You can also use the `pidfile` argument of `DaemonContext` with the `PIDLockFile` class from the `lockfile` package to properly support PID storing/retrieving and instance locking.
